// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAE5DvU1tkgzbrvGXJpnAufpBjFdYV9XY',
    appId: '1:714363988703:web:c2f714fedbc784929d176a',
    messagingSenderId: '714363988703',
    projectId: 'coffeeshop-bcecf',
    authDomain: 'coffeeshop-bcecf.firebaseapp.com',
    storageBucket: 'coffeeshop-bcecf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIGyi6Z1S3sUkN_PPOQl-rRO4rLSehI4',
    appId: '1:714363988703:android:2fb6fb54918f8b949d176a',
    messagingSenderId: '714363988703',
    projectId: 'coffeeshop-bcecf',
    storageBucket: 'coffeeshop-bcecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszzO1YHsN22pnkVfb_0Y4Fs2JcpQWBsY',
    appId: '1:714363988703:ios:ee6dbd3ab0c5c5489d176a',
    messagingSenderId: '714363988703',
    projectId: 'coffeeshop-bcecf',
    storageBucket: 'coffeeshop-bcecf.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCszzO1YHsN22pnkVfb_0Y4Fs2JcpQWBsY',
    appId: '1:714363988703:ios:ee6dbd3ab0c5c5489d176a',
    messagingSenderId: '714363988703',
    projectId: 'coffeeshop-bcecf',
    storageBucket: 'coffeeshop-bcecf.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAE5DvU1tkgzbrvGXJpnAufpBjFdYV9XY',
    appId: '1:714363988703:web:5430f9d7c9d3b7ed9d176a',
    messagingSenderId: '714363988703',
    projectId: 'coffeeshop-bcecf',
    authDomain: 'coffeeshop-bcecf.firebaseapp.com',
    storageBucket: 'coffeeshop-bcecf.firebasestorage.app',
  );
}
